#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Adrian Sampson"
email = "adrian@radbox.org"

[signing]
behavior = "own"
backend = "ssh"
key = "~/.ssh/id_rsa.pub"

[revsets]
log = "ancestors(@, 8) | ancestors(immutable_heads().., 2) | present(trunk())"
