#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Adrian Sampson"
email = "adrian@radbox.org"

[signing]
behavior = "own"
backend = "ssh"
key = "~/.ssh/id_ed25519.pub"

[revsets]
log = "ancestors(@, 8) | ancestors(immutable_heads().., 2) | present(trunk())"
bookmark-advance-to = "closest_pushable(@)"

[revset-aliases]
# https://docs.jj-vcs.dev/latest/config/#bookmark-advance-default-targets
"closest_pushable(to)" = '''
  heads(::to & mutable() & ~description(exact:"") & (~empty() | merges()))
'''
