"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
format = """$character"""
right_format = """
$git_status\
$git_branch\
$git_state\
$git_metrics\
$directory"""

[character]
success_symbol = """[\\$](bold green)"""
error_symbol = """[\\$](bold red)"""
vimcmd_symbol = """[\\$](bold purple)"""

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
symbol = ''
style = 'green'

[git_status]
format = '$ahead_behind$conflicted$untracked$modified '
untracked = '[●](bold red)'
modified = '[●](bold yellow)'

[directory]
format = '[$path]($style)[$read_only]($read_only_style)'
style = 'green'
